include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: false
    unawaited_futures: false
    cascade_invocations: false