name: flutter_projects
description: Flutter apps with amazing design and moderate animations

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.10.0
  flutter_staggered_grid_view: ^0.3.2
  cached_network_image: ^2.3.2+1
  auto_size_text: ^2.1.0
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/findout/
    - assets/img/medical/
    - assets/img/movie/
    - assets/img/music/
    - assets/img/