name: flutter_projects
description: Flutter apps with amazing design and moderate animations
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  cupertino_icons: ^1.0.0
#  google_fonts: ^1.1.1
#  flutter_vector_icons: ^0.2.1
#  flutter_staggered_grid_view: ^0.3.2
#  cached_network_image: ^2.3.3
#  flutter_svg: ^0.21.0-nullsafety.0

  cupertino_icons: ^1.0.3
  google_fonts: ^2.0.0
  flutter_vector_icons: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/findout/
    - assets/img/movie/
    - assets/img/music/
    - assets/img/superheroes/
    - assets/img/instagram/
    - assets/img/gaming/
    - assets/svg/instagram/
    - assets/svg/medical/
    - assets/img/books/
  fonts:
    - family: MDIcons
      fonts:
        - asset: assets/icons/md_icons/MdIcons.ttf